config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',registrations: 'users/registrations' }
  
  resources :torneos
  root :to  => 'torneos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/torneo.rb
class Torneo < ApplicationRecord
end

app/controllers/torneos_controller.rb
class TorneosController < ApplicationController
  before_action :set_torneo, only: [:show, :edit, :update, :destroy]
  layout "salir"

  # GET /torneos
  # GET /torneos.json
  def index
    @torneos = Torneo.all
  end

  # GET /torneos/1
  # GET /torneos/1.json
  def show
    @torneos = Torneo.find(params[:id])
    authorize! :read, @torneos
  end

  # GET /torneos/new
  def new
    @torneo = Torneo.new
  end

  # GET /torneos/1/edit
  def edit
  end

  # POST /torneos
  # POST /torneos.json
  def create
    @torneo = Torneo.new(torneo_params)

    respond_to do |format|
      if @torneo.save
        format.html { redirect_to @torneo, notice: 'Torneo was successfully created.' }
        format.json { render :show, status: :created, location: @torneo }
      else
        format.html { render :new }
        format.json { render json: @torneo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /torneos/1
  # PATCH/PUT /torneos/1.json
  def update
    respond_to do |format|
      if @torneo.update_attributes(uptade_params)
        format.html { redirect_to @torneo, notice: 'Torneo was successfully updated.' }
        format.json { render :show, status: :ok, location: @torneo }
      else
        format.html { render :edit }
        format.json { render json: @torneo.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_params
    params.require(:article).permit(:body)
  end

  # DELETE /torneos/1
  # DELETE /torneos/1.json
  def destroy
    @torneo.destroy
    respond_to do |format|
      format.html { redirect_to torneos_url, notice: 'Torneo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_torneo
      @torneo = Torneo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def torneo_params
      params.require(:torneo).permit(:evento, :nombre, :equipos_participantes, :localizacion, :organizador)
    end
    
    def create_params
    
    end 
end

app/helpers/torneos_helper.rb
module TorneosHelper
end

app/views/torneos/_form.html.erb
<%= form_with(model: torneo, local: true) do |form| %>
  <% if torneo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(torneo.errors.count, "error") %> prohibited this torneo from being saved:</h2>

      <ul>
      <% torneo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
<div class="row">

  <div class="col">
    <div class="field">
      <%= form.label :evento %>
      <%= form.text_field :evento, id: :torneo_evento , style: 'width: 60%', required: true %>
    </div>
  </div>  

  <div class="col">
    <div class="field">
      <%= form.label :nombre %>
      <%= form.text_field :nombre, id: :torneo_nombre, style: 'width: 60%', required: true %>
    </div>
  </div>
</div>

<br>

  <div class="row">
    <div class=col>
      <div class="field">
        <%= form.label :equipos_participantes %>
        <%= form.text_field :equipos_participantes, id: :torneo_equipos_participantes, style: "width: 60%", required: true %>
      </div>
    </div>
  
    <div class="col">
      <div class="field">
        <%= form.label :localizacion %>
        <%= form.text_field :localizacion, id: :torneo_localizacion,style: "width: 60%", required: true %>
      </div>
    </div>
  </div>
  
  <br>
  
 <div class="row">
   <div class="col">
      <div class="field">
        <%= form.label :organizador %>
        <%= form.text_field :organizador, id: :torneo_organizador,style: "width: 40%", required: true %>
      </div>
    </div>
  </div> 
  
  <br>
  

  <div class="container">
    <center>
      <div class="actions">
        <%= form.submit 'Guardar', class: 'btn btn-success' %>
      </div>
    </center>
  </div>
<% end %>
</div>

<br>

app/views/torneos/edit.html.erb
<div class="container">
    <center>
        <h1>Editar Torneo</h1> <hr> <br>
    </center>
</div>

<%= render 'form', torneo: @torneo %>

<div class="container">
 <%= link_to 'Atras', torneos_path, class:"btn btn-light" %>
</div>

app/views/torneos/index.html.erb
<p id="notice"><%= notice %></p>

<center>
<h1>Torneos</h1>
<br> <br>

<table class="table table-striped table-bordered" style="width: 50%">
  <thead>
    <tr>
      <th>Evento</th>
      <th>Nombre</th>
      <th>Equipos participantes</th>
      <th>Localizacion</th>
      <th>Organizador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @torneos.each do |torneo| %>
      <tr>
        <td><%= torneo.evento %></td>
        <td><%= torneo.nombre %></td>
        <td><%= torneo.equipos_participantes %></td>
        <td><%= torneo.localizacion %></td>
        <td><%= torneo.organizador %></td>
        <td><%= link_to 'Mostrar', torneo, class: 'btn btn-info' %></td>
        <% if can? :update, @torneos%>
        <td><%= link_to 'Editar', edit_torneo_path(torneo), class: 'btn btn-warning' %></td>
        <% end %>
        <td><%= link_to 'Eliminar', torneo, method: :delete, data: { confirm: '¿Estas seguro' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>

<br>

<div class="container">
<%= link_to 'Nuevo Torneo', new_torneo_path, class:"btn btn-success" %>
</div>

app/views/torneos/new.html.erb
 <div class="container">
 <center>
     <h1>Nuevo Torneo</h1>
 </center>
 <hr> <br>
 </div>
 
<%= render 'form', torneo: @torneo %>

<div class= "container">
    <%= link_to 'Atras', torneos_path, class:"btn btn-light" %>
</div>

app/views/torneos/show.html.erb
<div class="container">
   <center>
     <h1><%= @torneo.nombre%></h1> <hr> <br>
   </center> 
</div>

<div class="contaner">
  <center>
   <h3>Datos: <hr style="width: 10%"></h3>
   </center>
</div>


<div class="container">
  <div class="row">
    <div class ="col">
      <h5>Evento perteneciente:  <%= @torneo.evento %> </h5>
    </div>
 </div>  
 
   <div class="row">
      <div class="col">
          <h5>Nombre del Torneo: <%= @torneo.nombre %> </h5>
      </div>
   </div>
     
   <div class="row">
       <div class="col">
         <h5> Equipos participantes: <%= @torneo.equipos_participantes %> </h5>
      </div>
   </div>

  <div class="row">
    <div class="col">
      <h5>Localizacion del torneo: <%= @torneo.localizacion %></h5>  
    </div>
  </div>
  
  <div class="row">
    <div class="col">
      <h5>Organizador del evento: <%= @torneo.organizador %></h5>
    </div>
  </div>
</div>

 <br>

<div class="container">
  <%= link_to 'Editar', edit_torneo_path(@torneo), class: "btn btn-success" %>
  <%= link_to 'Atras', torneos_path, class: "btn btn-light" %>
</div>